# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:.
# https://aka.ms/yaml

#trigger:
#- master
trigger: none

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: DeployLinuxVM
  timeoutInMinutes: 300
  steps:
  - task: Bash@3
    displayName: Print Env variables
    inputs:
      targetType: 'inline'
      script: 'env | sort'  
  - task: AzurePowerShell@5
    displayName: Deploy VM and encrypt
    timeoutInMinutes: 300
    inputs:
      azureSubscription: 'Microsoft Azure Internal Consumption(4591c181-b2c0-4a55-93a9-f759859a214b)'
      ScriptType: 'FilePath'
      ScriptPath: 'vm-mgmt.ps1'
      ScriptArguments: '-Option $(OPTION) -ResourceGroupName $(RGName)'
      azurePowerShellVersion: 'LatestVersion'
  - task: AzureCLI@2
    displayName: Post encryption task
    timeoutInMinutes: 300
    inputs:
      azureSubscription: 'Microsoft Azure Internal Consumption(4591c181-b2c0-4a55-93a9-f759859a214b)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az vm run-command invoke -g $(RGName) -n vm1 --command-id RunShellScript --scripts "cd /home/zhenbo && wget https://raw.githubusercontent.com/zhenbzha/azure-linux-vm-encryption/master/post-encyrption.sh && chmod +x post-encyrption.sh && ./post-encyrption.sh"'
